### PR TITLE
chore: update to node 14, update deps, resolve yeoman

### PR DESCRIPTION
**Pull request by gbockus-sf**
### What does this PR do?
Update to require node 14 for this repo.
update yarn.lock files to updates from the latest as defined in package.json
resolve @types/yeoman to v4.11.0 

Note may need an additional commit to resolve security vulnerabilitites. 

### What issues does this PR fix or reference?
@W-10754639@

### CODE REVIEW

**Comment by gbockus-sf** [comment]
So I followed up on the synk failure.  There is a known issue with `lodash.set` that is introduced through `
@salesforce/command@4.2.2`.  There is currently no update to fix the issue.

**Review by mohanraj-r — COMMENTED** [review]
Can we try to add node 16 LTS (as 14 is maintenance LTS that will be unmaintained in about a year) and corresponding tsconfig with es target to match node 14?

**Comment by gbockus-sf** [comment]
> Can we try to add node 16 LTS (as 14 is maintenance LTS that will be unmaintained in about a year) and corresponding tsconfig with es target to match node 14?

@mohanraj-r Add a node-16 specific heroku build? Or were you referring to something else? 

I hesitate to touch the tsconfig  target as it's currently aligned with the extensions repo and we'll need to have a clear effort to get all the different modules on the same version.

**Comment by mohanraj-r** [comment]
@gbockus-sf Understand the concerns about modifying tsconfig. 
Yes I was referring to adding node16 to the job matrix (replacing node 12). But it looks like we also use `node-latest` img (not clear from [the build logs](https://app.circleci.com/pipelines/github/forcedotcom/salesforcedx-templates/1450/workflows/47644409-4a0c-431b-9022-110240f17154/jobs/5547) or [circleci docs](https://circleci.com/developer/images/image/cimg/node#image-tags) what version that translates to) - so maybe having node16 lts is redundant. Or maybe can we add a `node:lts` in addition to / instead of `node-latest`?

**Comment by gbockus-sf** [comment]
@mohanraj-r Good suggestion.  I assume latest is 17 since would be the installed version with docker using the latest tag. I added the node 16 test

**Review by jag-sfdc — APPROVED** [review]

**Review by jeffb-sfdc — APPROVED** [review]

**Comment by jag-sfdc** [comment]
@gbockus-sf - I have changed this. This is in branch -> branch protection rules. Will send some screenshots to the team's slack channel.

**Pull request merged**
