### PR TITLE
Fix for "No matching version found for prettier-plugin-apex@^1.10.1" on npm install

### PR DESCRIPTION
**Pull request by benjaminloerincz**
After creating a project using `sfdx force:project --projectname=newproject`, this error message appears on `npm install` in the project folder:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for prettier-plugin-apex@^1.10.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benjaminloerincz/.npm/_logs/2021-12-23T14_17_36_183Z-debug-0.log
```

### What does this PR do?

This PR changes the version number for prettier-plugin-apex.

### What issues does this PR fix or reference?

- [394](https://github.com/forcedotcom/salesforcedx-templates/issues/394)
- [398](https://github.com/forcedotcom/salesforcedx-templates/issues/398)

### CODE REVIEW

**Comment by forcetrekker** [comment]
@randi274 @gbockus-sf Could you please take a action on this PR. :)

**Comment by randi274** [comment]
Thanks for your patience @benjaminloerincz! I will take this on today.

**Comment by randi274** [comment]
Confirmed the issue, and will test the fix on a new branch. We'll merge that one in and close this PR once that's complete, since our automation doesn't run on contributor PRs. Stay tuned!

**Review by randi274 — APPROVED** [review]

**Comment by randi274** [comment]
Thanks for your contribution! This is now merged @benjaminloerincz, and should be available with the update to the CLI tomorrow. Let us know if you experience any further issues with this, and hopefully it won't take us a month+ to respond next time :)

**Pull request closed without merging**
